<script src="<?php echo base_url(); ?>js/bantuan.js" type="text/javascript" charset="utf-8"></script>
<style>
   ol { counter-reset: item; padding-left: 13px; display: table;}
   .number-list li { display: block; display: table-row;}
  .number-list li:before { content: counters(item, ".") ". "; counter-increment: item; display: table-cell;}
</style>
<div id="content">
    <div class="blank" style="height:30px;"></div>
    <div id="bantuan">
        <table>
            <tr>
                <td>
                    <div id="bantuan-faq">
                        <div id="bf-header">
                            <div id="bf-header-wrap">
                                SYARAT DAN KETENTUAN
                            </div>
                        </div>
                        <div id="bf-content">
                            <div class="blank" style="height: 20px;"></div>
                            <div class="bfc-wrap">
                                <div class="bfc-title">

<p class="bold center">Syarat dan Ketentuan</p>
<p>PERSYARATAN DAN KETENTUAN DI BAWAH INI WAJIB DIBACA SEBELUM MENGGUNAKAN SITUS INI. PENGGUNAAN SITUS INI BERARTI PENERIMAAN DAN PENUNDUKAN DIRI TERHADAP SYARAT DAN KETENTUAN YANG ADA DI BAWAH INI.</p>
<p>Penggunaan situs www.ruangguru.com ("Situs"), yang dikelola oleh PT. Ruang Raya Indonesia ("Kami"), adalah berdasarkan penerimaan dan penundukan terhadap Syarat dan Ketentuan Penggunaan di bawah ini termasuk namun tidak terbatas pada Kerahasiaan, FAQs , dan judul judul lainnya yang menjadi suatu bagian tak terpisahkan dari Syarat dan Ketentuan dan termasuk di dalamnya referensi dan istilah yang digunakan ("Syarat"). Syarat ini dapat kami ubah, modifikasi, tambah dan hapus sewaktu-waktu tanpa pemberitahuan. Syarat wajib secara berkala dibaca. Dengan melanjutkan penggunaan Situs ini setelah perubahan yang ada pada Syarat, berarti pengunjung, pengguna, Pengguna Terdaftar ("Anda" atau "Pengguna") menyatakan setuju dan sepakat terhadap perubahan yang ada. Apabila Anda menggunakan jasa lain milik Kami, maka penggunaan Anda akan berdasarkan penundukan terhadap Syarat dan Ketentuan yang berlaku bagi jasa tersebut.</p>
<br/>
<p  class="bold">1. HAK INTELEKTUAL PROPERTI</p>
<p>Segala Hak Kekayaan Intelektual yang ada di dalam Situs ini adalah kepunyaan dari Ruangguru. Semua informasi dan bahan-bahan, termasuk tetapi tidak terbatas pada, perangkat lunak, teks, data, grafik, gambar, suara, video, logo, ikon atau kode-kode html dan kode-kode lain yang ada di website ini dilarang dipublikasikan, dimodifikasi, disalin, digandakan atau diubah dengan cara apapun di luar area Situs ini tanpa izin dari Ruangguru. Pelanggaran terhadap hak-hak Situs ini dapat ditindak sesuai dengan peraturan yang berlaku</p>
<p class="bold">TAUTAN DAN KONTEN</p>
<p>Situs dapat memuat tautan ke situs yang dioperasikan oleh pihak-pihak selain Ruangguru. Tautan-tautan tersebut disediakan hanya sebagai referensi untuk Anda. Kami tidak mengendalikan situs ataupun tautan tersebut dan tidak bertanggung jawab atas isi atau privasi maupun praktek-praktek lain dari situs tersebut. Selanjutnya, tidak ada pihak yang menjamin keakuratan atau kelengkapan informasi atau konten pada tautan yang disertakan pada Situs.</p>
<p>Kami, atau pihak ketiga lainnya, dapat memuat hasil pencarian otomatis atau menyediakan tautan/link kepada situs lain. Kami dapat menyediakan kesempatan bagi pihak ketiga untuk menyampaikan, memuat, mengirimkan atau menyediakan informasi, data, tulisan, foto, suara, grafis, video, pesan, review, atau bahan lainnya ("Konten") melalui Situs ini. Kami tidak mereview dan/atau tidak memiliki kontrol terhadap situs, sumber, dan Konten, Anda dengan ini menyatakan menerima bahwa Kami tidak bertanggung jawab terhadap Konten yang ada, atau ketersediaan situs dan sumber tersebut, dan kami tidak mendukung atau menyarankan dan tidak bertanggung jawab atas situs atau asal muasal Konten. Anda dengan ini menyatakan sepakat untuk melepaskan Kami dari dan terhadap setiap dan seluruh kewajiban, tanggungan baik secara langsung ataupun tidak langsung, atas kerugian, kerusakan, yang diakibatkan atau dituduhkan sebagai akibat dari atau sehubungan dengan penggunaan atau dipertanggungjawabkannya suatu Konten, situs atau sumber.</p>
<p class="bold">3. LARANGAN PENGGUNAAN</p>
<p>Anda dengan ini sepakat untuk tidak menggunakan Situs atau Konten ini untuk hal yang melawan hukum atau aktivitas tanpa izin, Anda sepakat bahwa Anda tidak akan menggunakan peralatan, perangkat lunak, atau teknologi lain yang dapat menghalangi atau berupaya untuk menghalangi cara kerja Situs ini. Anda sepakat untuk tidak menggunakan Situs ini atau Kontennya untuk tujuan komersial. Anda sepakat untuk tidak mengupayakan, membuat atau mengupayakan, mencari, mengutus agen otomatis atau teknologi bentuk lainnya untuk mengumpulkan, mendapatkan, atau hal lainnya untuk berinteraksi dengan Situs ini.</p>
<p class="bold">4. TIDAK ADA PENJAMINAN</p>
<p>ANDA DENGAN INI MENYATAKAN SEPAKAT DAN SETUJU BAHWA SEJAUH MANA DIIZINKAN OLEH PERATURAN YANG BERLAKU:</p>
<p>(a) JASA DAN KONTEN DARI SITUS INI DISEDIAKAN DENGAN KETENTUAN "SEBAGAIMANA ADANYA" DAN "SEBAGAIMANA TERSEDIA". KAMI DENGAN INI MENYATAKAN DENGAN TEGAS BAHWA KAMI TIDAK MELAKUKAN PENJAMINAN ATAU GARANSI APAPUN BAIK SECARA TEGAS MAUPUN TERSIRAT, SEHUBUNGAN DENGAN DAPAT DIPERDAGANGKAN SUATU PRODUK ATAU JASA, ATAU KESIAPAN SUATU PRODUK DAN JASA YANG KAMI SEDIAKAN UNTUK SUATU TUJUAN TERTENTU DAN TERHADAP PELANGGARAN YANG BERLAKU;</p>
<p>(b) KAMI TIDAK MENJAMIN BAHWA</p>
<p>(i) FUNGSI DAN JASA YANG DISEDIAKAN DARI SITUS INI AKAN BEBAS DARI GANGGUAN ATAU KESALAHAN APAPUN TERMASUK KEAMANAN DARI SITUS INI;</p>
<p>(ii) KELALAIAN AKAN DI PERBAIKI; ATAU</p>
<p>(iii) SITUS INI ATAU SERVER YANG MENYEDIAKAN JASA BEBAS DARI VIRUS ATAU KOMPONEN MEMBAHAYAKAN;</p>
<p>(c) KAMI TIDAK MENJAMIN MENGENAI KETEPATAN, KEASLIAN, INTEGRITAS ATAU KUALITAS DARI KONTEN, SITUS ATAU SUMBER YANG ADA PADA DAN DARI SITUS, TERMASUK, NAMUN TIDAK TERBATAS PADA PENJAMINAN KONTEN, SITUS ATAU SUMBER YANG BEBAS DARI BAHAN YANG DAPAT MENYERANG, TIDAK SENONOH, ATAU DAPAT DIPERDEBATKAN;</p>
<p>(d) TIAP BAHAN YANG DIUNDUH ATAU DIPEROLEH MELALUI PENGGUNAAN JASA INI ADALAH TANGGUNGJAWAB DAN RISIKO ANDA SENDIRI. ANDA AKAN BERTANGGUNGJAWAB SEPENUHNYA TERHADAP KERUSAKAN SISTEM KOMPUTER ATAU KEHILANGAN DATA YANG DIAKIBATKAN DARI PENGUNDUHAN MATERI YANG ADA.</p>
<p class="bold">5. PEMBATASAN PERTANGGUNGJAWABAN</p>
<p>KAMI TIDAK AKAN BERTANGGUNGJAWAB TERHADAP KERUSAKAN DARI PENGGUNAAN SITUS INI BAIK SECARA LANGSUNG MAUPUN TIDAK LANGSUNG, BAIK KHUSUS ATAU TAMBAHAN SEBAGAI PENGGUNAAN SITUS INI ATAU PENGGUNAAN DARI TAUTAN YANG ADA PADA SITUS WALAUPUN KAMI TELAH DIBERITAHU MENGENAI KEMUNGKINAN KERUGIAN ATAU KERUSAKAN YANG DAPAT TERJADI. PERBAIKAN YANG DAPAT DIBERIKAN PADA ANDA ADALAH PEMBERHENTIAN DARI PENGGUNAAN SITUS INI.</p>
<p class="bold">6. INDEMNIFIKASI</p>
<p>Anda dengan ini menyatakan sepakat untuk membebaskan dan melepaskan Ruangguru, karyawan, afiliasi, staf, partner, dari dan terhadap setiap dan seluruh tuntutan atau permintaan, termasuk biaya konsultan hukum yang wajar, yang muncul sebagai akibat tuntutan pihak ketiga sehubungan dengan penggunaan Situs; Konten yang diberikan, disediakan melalui Situs ini; pelanggaran terhadap Syarat; dan/ atau pelanggaran terhadap hak atau kewajiban lain.</p>
<p class="bold">7. LINGKUP PENYEDIAAN JASA</p>
<p>Melalui Situs, Ruangguru menyediakan platform online di mana mempertemukan antara calon murid dengan calon guru untuk belajar secara privat, Kami akan memberikan konfirmasi pemesanan guru melalui konfirmasi e-mail. Kami berhak untuk menolak pemesanan seperti yang ditetapkan di bawah ini.</p>
<p>Meskipun kami akan menggunakan keahlian kami dengan hati-hati dalam melaksanakan jasa, kami akan melakukan verifikasi, dan dapat menjamin bahwa semua informasi yang diberikan adalah akurat, lengkap, benar atau terbaru, dan kami tidak dapat bertanggung jawab atas segala kesalahan (termasuk penempatan dan kesalahan pengetikan), halangan (entah karena salah (sementara dan/ atau sebagian), kerusakan, perbaikan, peningkatan atau perbaikan Situs atau hal lainnya).</p>
<p>Kami memiliki hak untuk tidak menerima pengguna atau pemesanan (atau dalam hal-hal tertentu membatalkan konfirmasi pemesanan) atas diskresi Kami dan untuk alasan apapun tanpa perlu memberikan alasan penolakan/ pembatalan yang ada. Alasan utama penolakan pelanggan atau pemesanan termasuk namun tidak terbatas pada; pelanggaran Syarat, sanksi perdagangan atau ekonomis, larangan peraturan, penipuan atau pencurian (atau indikasi maupun kecurigaan terhadapnya), sangkaan tindakan kriminal, pemesanan yang mencurigakan, penyampaian oleh pelanggan dalam hal kesalahan atau penyesatan informasi, masalah kartu kredit, prilaku tidak pantas, ancaman, hinaan, penolakan untuk memberikan informasi, halangan praktis, masalah komunikasi, kesalahan nyata (selanjutnya diatur di bawah), riwayat, dimasukan dalam daftar hitam oleh pemerintah atau organisasi internasional. Dalam hal pemesanan ditolak atau dibatalkan oleh Ruangguru dan pembayaran telah dilakukan, maka Anda akan menerima pengembalian dari total pemesanan yang telah dilakukan. Kami dapat sewaktu-waktu menghapus atau menghilangkan ("Dihapus") keanggotaan dari Pengguna Situs ini, baik untuk sementara atau untuk selamanya. Pengguna yang Dihapus tidak boleh melakukan percobaan penggunaan Situs dalam nama lain atau melalui Pengguna lainnya (selanjutnya diatur dalam Mekanisme Pencegahan Penipuan).</p>
<p>Dalam suatu kasus tertentu, Kami dapat melakukan pembatalan atau penolakan pemesanan sehubungan dengan "kesalahan nyata", yang tidak tergantung dari mana kesalahan itu berasal. Untuk lebih jelas, bahwa kesalahan nyata adalah suatu kesalahan pada Situs (contohnya dalam hal harga) di mana orang sewajarnya tidak akan menganggap hal tersebut sebagai hal biasa. Jumlah yang dibebankan atau perbedaannya akan tetap ditagihkan, dan Ruangguru memiliki hak diskresi untuk menolak atau membatalkan pemesanan ini.</p>
<p>Keadaan seperti adanya renovasi, kesalahan pemesanan, dan permintaan khusus pelanggan wajib diberitahukan kepada pihak Ruangguru.</p>
<p class="bold">8. RATING</p>
<p>Rating yang ada hanya disediakan untuk guru saja, rating yang diberikan berdasarkan verifikasi dari kesamaan antara dokumen identitas dan juga jejak rekam mengajar Ruangguru yang dinilai berdasarkan feedback Murid.</p>
<p class="bold">9. PENGGUNAAN SITUS</p>
<p>Ruangguru dengan ini memberikan Pengguna suatu hak yang tertentu yang terbatas, tidak dapat dialihkan atau dipindahtangankan, untuk mengakses dan menggunakan Situs sejauh mana diperbolehkan dengan tegas oleh Syarat. Sehubungan dengan lisensi terbatas, Kami dengan tegas menyatakan tidak memberikan hak atau lisensi sehubungan dengan penggunaan Situs; hak atau lisensi yang tidak dengan tegas diberikan, dimiliki sepenuhnya oleh Ruangguru atau pihak ketiga lainnya pemilik lisensi tersebut. Konten yang ada pada Situs, berikut juga perangkat lunak, infrastruktur yang digunakan untuk menyediakan Konten, sepenuhnya dimiliki oleh Ruangguru. Anda dapat menggunakan Situs untuk melakukan pemesanan dan Anda dengan ini menyatakan menjamin bahwa Anda tidak akan melakukan pemesanan palsu atau spekulatif terhadap antisipasi permintaan pemesanan yang mungkin ada. Anda dengan ini menyatakan menjamin bahwa informasi pembayaran yang Anda berikan pada Kami adalah benar, tepat dan akurat sepenuhnya. Anda juga menyatakan menjamin untuk menyediakan alamat surat elektronik, alamat surat-menyurat dan/ atau rincian informasi yang dapat dihubungi yang tepat dan akurat.</p>
<p>Sehubungan dengan persyaratan penggunaan Situs, Anda sepakat untuk tidak menggunakan Situs atau Konten untuk tujuan komersial atau baik secara langsung atau tidak untuk selain keperluan pribadi atau untuk tujuan yang melawan hukum, dilarang oleh hukum atau perbuatan yang melanggar Syarat. Kecuali dengan persetujuan tertulis dari Ruangguru, Anda sepakat untuk tidak mengubah, menyalin, membagikan, mengirimkan, menampilkan, melaksanakan, mereproduksi, mengumumkan, mengizinkan, mencipatakan kreasi derivatif dari, mengalihkan, atau menjual atau menjual kembali tiap informasi, perangkat lunak, produk atau jasa yang diperoleh sehubungan dengan Situs. Sebagai tambahan, Anda sepakat untuk tidak:</p>
<p>1. Menggunakan Situs ini atau Konten untuk tujuan komersial tanpa seizin Ruangguru;</p>
<p>2. Mengakses, mengawasi atau menyalain tiap Konten dalam Situs 3. Menggunakan teknologi, perangkat lunak, program apapun baik secara manual ataupun otomatis untuk tujuan lain tanpa izin tegas tertulis dari Ruangguru;</p>
<p>3. Melakukan tindakan yang mengakibatkan atau dapat mengakibatkan, suatu beban yang tidak wajar pada infrastruktur Kami;</p>
<p>4. Membuat suatu tautan utama bagi Situs (termasuk namun tidak terbatas pada jalur pemesanan) untuk tujuan apapun tanpa persetujuan tertulis Ruangguru;</p>
<p>5. Menjual kembali, menggunakan, menyalin, melakukan pengawasan (contoh memasang spider, scrape), menampilkan, mengunduh atau melakukan produksi tiap Konten, perangkat lunak, produk, jasa yang tersedia dalam Situs untuk tujuan komersil atau tujuan/kegiatan persaingan usaha;</p>
<p>6. Melakukan percontohan ("frame" atau "mirror") atau mendirikan bagian dari Situs ini pada Situs web lainnya tanpa persetujuan tertulis terlebih dahulu;</p>
<p>mengirimkan suatu pengumuman kepada atau melalui Situs yang melawan hukum berdasarkan hukum peraturan yang berlaku, ataupun pengumuman yang dapat mendukung kegiatan kriminal;</p>
<p>7. Mengirimkan atau menyediakan tautan kepada atau pengumuman yang mengandung suatu materi yang dapat dianggap membahayakan, cabul, berbau pornografi, tidak senonoh, berbau kekerasan, rasis, diskriminasi, penghinaan, pengancaman, pelecehan, penindasan, kebencian atau tidak pantas;</p>
<p>8. Mengirimkan atau menyediakan tautan kepada tiap pengumuman yang mengandung hal pencemaran nama baik, fitnah, dan kebohongan;</p>
<p>mengirimkan atau melakukan pengumuman yang dapat melanggar dan menyalahi hak intelektual property atau hak lainnya dari badan atau orang tertentu termasuk namun tidak terbatas pada hak cipta, hak paten, hak merek, rahasia dagang, kerahasiaan, atau publikasi;</p>
<p>9. Mengirimkan pengumuman yang mana dilarang oleh hukum yang berlaku atau melanggar hak dan kewajiban yang ada berdasarkan hubungan kontrak;</p>
<p>10. Meniru orang atau badan atau memalsukan keadaan atau memberikan gambaran yang salah terhadap suatu afiliasi akan seseorang atau badan atau mengambil identitas palsu apabila tujuannya adalah untuk menyesatkan, membohongi atau menipu;</p>
<p>11. Memanipulasi, memalsukan dengan tujuan menyamarkan asal dari pengumuman yang Anda berikan;</p>
<p>12. Menggunakan Situs ini dengan cara yang dapat merusak, melumpuhkan, menghalangi, atau mengganggu penggunaan Situs atau pengguna peralatan komputer lainnya, atau mengakibatkan kerusakan, gangguan atau membatasi fungsi dari perangkat lunak, perangkat keras atau peralatan telekomunikasi;</p>
<p>13. Mencoba untuk mendapatkan akses terhadap penggunaan yang tidak sah atas Situs atau Situs web terkait lainnya, akun lain, system komputer, jaringan yang terhubung dengan Situs melalui hacking, pencurian kata sandi atau hal serupa lainnya;</p>
<p>14. Mendapatkan atau berupaya mendapatkan materi atau informasi melalui cara-cara yang bukan sengaja disediakan oleh Situs (termasuk namun tidak terbatas tujuan lain penyediaan oleh Situs), termasuk namun tidak terbatas dalam mendapatkan atau mengumpulkan informasi tentang pihak lainnya seperti alamat email;</p>
<p>15. Terlibat dalam tindakan penipuan atau tindakan yang ditujukan untuk memanipulasi suatu engine pencarian halaman (SERP) atau mempekerjakan engine pencarian optimal (SEO) yang dianggap bertentangan dengan engine pencarian umumnya. Praktek SEO dianggap suatu tindakan yang tidak etis atau "spamdexing" termasuk namun tidak terbatas pada penyelubungan, meta data, tag judul, scraping konten, skema link, bom google, pencarian kata kunci, text tersembunyi atau tautan tersembunyi, skema tautan, komentar mengandung spam dan hal lainnya; atau</p>
<p>16. Melakukan tindakan lainnya yang dapat mengakibatkan kerusakan pada Situs, Ruangguru atau afiliasinya dan termasuk karyawannya, reputasi Ruangguru atau hal lain yang dapat menimbulkan dampak negatif.</p>
<p>17. Kecuali ditentukan dengan tegas sebaliknya, Situs web tidak diperbolehkan melakukan tautan kepada halaman lainnya selain daripada halaman utama Situs atau frame Situs atau halaman web atau bahan yang ada didalamnya, atau melakukan tautan terhadap aspek Situs dalam bentuk email dengan tujuan komersil tanpa mendapatkan persetujuan tertulis yang tegas oleh Ruangguru.</p>
<p>18. Dengan melakukan pemesanan melalui Situs, Anda dengan ini menyatakan dan menjamin bahwa Anda tidak dalam keadaan dilarang atau dibatasi oleh program sanksi apapun.</p>
<p class="bold">10. HARGA, TAMBAHAN BIAYA dan Promo</p>
<p class="bold">A. HARGA dan Promo</p>
<p>Harga yang lebih rendah hanya tersedia atas kesepakatan dari guru yang bersangkutan dengan persyaratan yang berbeda misalnya sehubungan dengan pemesanan dan kebijakan pengembalian.</p>
<p class="bold">B. Tambahan Biaya</p>
<p>Tiap harga yang tertera pada Situs hanya tersedia dengan persyaratan tertentu dan memungkinkan adanya perubahan yang terjadi tergantung pada ketersediaan pemesanan, jangka waktu dan/atau kuota. Harga yang tersedia dapat termasuk pajak dan tambahan biaya lainnya lagi namun dalam hal dan keadaan tertentu dapat juga tidak termasuk pajak dan biaya jasa, Pengguna diharapkan untuk memperhatikan total biaya yang harus dibayarkan berikut perinciannya pada saat konfirmasi dikirimkan kepada email Pengguna. Pengguna diharapkan untuk memverifikasi pemesanan pada lembar pemesanan; Pengguna dapat membatalkan pemesanan setiap saat sebelum konfirmasi terakhir dilakukan. Harga yang tertera akan dirinci sehingga Pengguna dapat melihat jumlah yang harus dibayar, tiap tambahan biaya dikarenakan penggunaan kartu kredit atau biaya yang dikenakan antar bank karena pengiriman biaya akan dikenakan kepada Pengguna dan apabila terdapat kekurangan dalam jumlah yang dibayarkan maka Ruangguru dapat memberikan email notifikasi mengenai kekurangan jumlah yang harus dibayarkan oleh Pengguna. Dalam hal dalam jangka waktu yang diberikan Pengguna masih belum juga membayarkan kekurangan biaya yang ada maka Pengguna dianggap membatalkan pemesanan, Ruangguru dapat melakukan pengembalian dalam jumlah penuh atau mengembalikan jumlah yang telah dipotong dengan biaya yang dikeluarkan oleh Ruangguru sebagai akibat dari tidak dibayarnya biaya kekurangan tersebut oleh Pengguna dalam jangka waktu sesuai prosedur yang ditentukan oleh Ruangguru. Apabila terdapat keraguan mengenai jasa dan pelayanan maka Pengguna dapat menghubungi layanan pelanggan Ruangguru (selama jam operasional layanan pelanggan yang ditentukan oleh Ruangguru). Kami bukan pihak yang memungut pajak, tiap pungutan dan pembebanan pajak akan ditanggung oleh Ruangguru atau Pengguna tergantung dari jenis pajak dan pungutan sesuai dengan peraturan yang berlaku</p>
<p class="bold">C. Mata Uang</p>
<p>Pembayaran dilakukan dalam mata uang rupiah, dengan jumlah sesuai dengan yang tertera tanpa penanggungan biaya bank atau biaya lainnya oleh Ruangguru.</p>
<p class="bold">11. KERAHASIAAN</p>
<p>Kami akan berupaya menjaga kerahasiaan Anda. Kebijakan Kerahasiaan akan diatur lebih lanjut dalam di bawah.</p>
<p class="bold">12. PEMBAYARAN-PENIPUAN</p>
<p>Untuk pembayaran Pemesanan melalui Situs, Anda akan ditagih oleh Ruangguru untuk harga penuh (pengembalian dana yang terjadi tergantung pada kondisi Pemesanan yang ada) pada saat pemesanan dan konfirmasi pemesanan. Silakan memeriksa detail pemesanan secara menyeluruh untuk setiap saat tersebut sebelum Anda membuat pemesanan. Ruangguru akan memproses pengembalian uang, sebagaimana berlaku, dalam jangka waktu yang wajar. </p>
<p>Dalam hal penipuan atau penggunaan yang tidak sah dari pembayaran Anda oleh pihak ketiga, Anda harus menghubungi bank segera setelah menyadari penggunaan yang tidak sah tersebut. Jika Anda mencurigai adanya pemesanan yang tidak sah atau penipuan yang dilakukan melalui Ruangguru, silakan hubungi tim Layanan Pelanggan kami segera.</p>
<p>Untuk melakukan pemesanan Anda harus berusia lebih dari 18 tahun dan memiliki kapasitas hukum penuh untuk membuat transaksi (atau memiliki otorisasi dari wali hukum Anda). Anda wajib menggunakan kartu kredit atau debit milik Anda sendiri dan memastikan bahwa ada dana yang cukup untuk menutupi biaya transaksi. Anda menerima tanggung jawab keuangan untuk semua transaksi yang dilakukan atas nama Anda atau akun Anda.</p>
<p>Anda wajib memastikan bahwa rincian Anda berikan kepada Kami dengan dalam membuat pemesanan sepenuhnya adalah benar, tepat dan akurat. Ruangguru berhak untuk tidak menerima kartu kredit tertentu. Ruangguru dapat menambah atau menghapus metode pembayaran lainnya dengan kebijakannya sendiri.</p>
<p>Dalam kasus tertentu, kami mungkin membutuhkan informasi tambahan atau verifikasi untuk memvalidasi dan mengkonfirmasi pemesanan, seperti yang dijelaskan secara lebih rinci di Situs. Pemesanan tidak dikonfirmasi sampai Anda telah menerima email konfirmasi dengan voucher dan ada kemungkinan bahwa vendor dapat melaksanakan pemeriksaan penipuan selama pemesanan diproses, dalam hal penipuan terjadi maka pemesanan tidak akan lagi tersedia atau otomatis menjadi batal. Ruangguru tidak dapat dimintai pertanggungjawaban dalam kasus tersebut. Jika Anda memilih untuk tidak menyampaikan informasi tambahan, pemesanan tidak akan selesai dan sepenuhnya menjadi batal.</p>
<p class="bold">13.PERSYARATAN PEMESANAN � PEMBATALAN� PERMINTAAN TERTENTU</p>
<p>Sehubungan dengan pembatalan yang dilakukan Pengguna, maka Ruangguru mungkin akan dapat menahan atau mengambil bagian dari jumlah yang dibayarkan untuk mengganti biaya yang telah dikeluarkan sehubungan dengan pembatalan yang terjadi.</p>
<p>Pengguna diharapkan membaca dan mengerti Syarat dan Ketentuan yang ada pada registrasi guru, murid, duta dan pesan guru.</p>
<p class="bold">14. HAK INTELEKTUAL PROPERTI</p>
<p>Nama domain, Situs, logo, dan hak intelektual property lainnya dimiliki sepenuhnya oleh Ruangguru dan/atau afiliasinya. Produk lain dan nama perusahaan yang ada ada pada Situs adalah nama, merek dagang, merek, tanda jasa, logo, symbol atau design lainnya ("Hak Intelektual Properti") milik Ruangguru atau perusahaan asosiasi atau pihak ketiga lainnya. Penggunaan atas Hak Intelektual Properti yang ada pada Situs, tidak dapat dianggap sebagai rekomendasi atau sponsor bagi Situs oleh pihak ketiga tersebut. Ruangguru memiki hak cipta atas Situs, dan Anda dilarang menggunakan Hak Intelektual Properti tanpa persetujuan Ruangguru.</p>
<p>Situs dapat mengandung materi Hak Intelektual Properti termasuk namun tidak terbatas pada tulisan, perangkat lunak, foto, grafis dan mungkin video, music dan suara. Keseluruhan dari Konten Situs dilindungi oleh undang-undang hak cipta. Kami dan para pemegang lisensi memiliki hak cipta dan/atau hak lainnya atas pemilihan, koordinasi, pengaturan, dan perbaikan Konten berikut konten asal yang ada. Anda dilarang untuk mengubah, menampilkan, mempublikasikan, mengeksploitasi ikut serta dalam suatu tindakan penjualan atas Konten dan konten asalnya, baik secara keseluruhan atau sebagian kecuali dinyatakan sebaliknya dengan tegas dalam Syarat ini.</p>
<p>Kecuali ditentukan sebaliknya, maka perangkat lunak yang diperlukan bagi penyediaan jasa atau tersedia untuk digunakan pada Situs dan Hak Intelektual Properti dalam Konten pada Situs dimiliki oleh Ruangguru, afiliasinya atau perusahaan asosiasinya, pemberi izin, supplier dan penyedia Konten. Ruangguru tidak bertanggung jawab atas Hak Intelektual yang disediakan oleh pihak ketiga atau atas pelanggaran Hak Intelektual Properti milik pihak ketiga tersebut.</p>
<p>Anda dapat menggunakan informasi dalam Situs hanya untuk penggunaan pribadi non komersil. Kecuali ditentukan sebaliknya dan diperbolehkan secara tegas oleh undang-undang hak cipta, maka Pengguna dilarang menyalin, membagikan ulang, mentransmisi ulang, mempublikasi atau melakukan tindakan eksploitasi komersial dari pengunduhan yang dilakukan tanpa seizin pemilik Hak Intelektual Properti tersebut. Dalam hal Pengguna telah mendapatkan izin yang diperlukan maka Pengguna dilarang melakukan perubahan atau penghapusan. Pengguna dengan ini menyatakan menerima dan mengetahui bahwa dengan mengunduh materi Hak Intelektual Properti bukan berarti mendapatkan hak kepemilikan atas pengunduhan materi Hak Intelektual Properti tersebut.</p>
<p>Kami dapat menyediakan tautan kedalam Situs lain yang dikelola oleh pihak lain, dengan mengklik tautan tersebut Pengguna dengan ini menyatakan mengetahui dan setuju bahwa tindakan tersebut adalah tindakan yang dilakukan atas tanggung jawab pribadi Pengguna yang telah dengan sukarela memasuki situs lain bukan berada dalam pengawasan dan tanggungjawab Ruangguru.</p>
<p>Ruangguru dalam membuat Situs berikut penyusunan source code dan perangkat lunak pendukung, dapat menggunakan lisensi dari pihak ketiga lainnya baik berupa open source (GNU/GPL) dan telah terdapat modifikasi yang merupakan milik kepunyaan Ruangguru. Setiap penggunaan dari open source dan Hak Intelektual Properti milik pihak ketiga telah mendapatkan ijin yang diperlukan.</p>
<p class="bold">Tuntutan atas Pelanggaran Hak Intelektual Properti</p>
<p>Apabila terdapat bukti pelanggaran Hak Intelektual Properti Anda dilanggar maka Anda atau wakil Anda ("Pengirim") dapat mengirimkan surat pemberitahuan berisi hal berikut di bawah ini:</p>
<ol>
	<li>Nama dan alamat Pengirim;</li>
	<li>Dalam hal Pengirim bukan pemilik Hak Intelektual Properti atau lisensi eksklusif maka wajib mencantumkan nama dan alamat pemilik Hak Intelktual Properti;</li>
	<li>Dalam hal terdapat alamat pengirim bukan berasal dari Indonesia, maka wajib mengirimkan alamat sementara di Indonesia;</li>
	<li>Nomor telepon, faksimili (apabila ada) dan alamat surat elektronik yang dapat dihubungi;</li>
	<li>Rincian yang secukupnya sehingga dapat membuktikan adanya Hak Intelktual Properti yang dilanggar;</li>
	<li>Rincian yang secukupnya sehingga dapat mengenali dan mendapatkan adanya Hak Intelktual Properti yang dilanggar termasuk alamat online dari kopi elektronik yang ada;</li>
	<li>Pernyataan Pengirim untuk menghapuskan atau melumpuhkan akses kepada salinan elektronik yang dilanggar tersebut;</li>
	<li>Pernyataan bahwa Pengirim dengan itikad baik mengenali adanya pelanggaran sebagaimana dikenali pada angka 5 Pasal ini;</li>
	<li>Pernyataan dalam pemberitahuan bahwa informasi yang diberikan adalah akurat;</li>
	<li>Pernyataan bahwa Pengirim adalah<br/>
		<p>(a) pemilik atau pemegang hak eksklusif atas Hak Intelektual Properti yang dilanggar tersebut; atau </p>
		<p>(b) kuasa yang sah untuk bertindak atas pemilik atau pemegang hak eksklusif tersebut; dan</p>
	</li>
	<li>Pernyataan bahwa Pengirim tunduk pada Hukum Indonesia dan memilih forum hukum Mediasi pada Pusat Mediasi Nasional yang ditunjuk dan disediakan oleh Ruangguru apabila terjadi sengketa berdasarkan Undang-Undang Hak atas Intelektual Properti. </li>
	<li>Surat tersebut wajib ditandatangani oleh Pengirim dan dikirimkan secara fisik dan melalui email ke alamat berikut ini: <br/>
		<p>
		<strong>PT. Ruang Raya Indonesia</strong><br/>
		d/a: Indonesian Future Leaders<br/>
		Ruangan A.220, Universitas Siswa Bangsa Internasional<br/>
		Jl. MT. Haryono Kav. 58-60, Pancoran<br/>
		Jakarta Selatan, Indonesia, 12780<br/>
		Telepon : 021-9200-3040
		</p>
		<p>Kami akan mereview dan menangani pemberitahuan yang sesuai dengan persyaratan di atas dan sesuai dengan peraturan Hukum Indonesia yang berlaku.</p>
		<p>Kami menyarankan Anda untuk mengkonsultansikan dulu sebelum tuntutan dikirimkan, dan Anda dengan ini menyatakan bertanggung jawab secara pribadi atas kerugian atau kerusakan yang mungkin terjadi sebagai akibat pemalsuan atau tuduhan palsu pelanggaran Hak Intelektual Properti.</p>
		<p>Ketentuan dalam pasal ini juga berlaku dalam hal tuntutan, perselisihan, persengketaan, dan penafsiran yang timbul dari dan atas penggunaan Situs dan pelaksanaan Syarat.</p>
	</li>
</ol>
<p class="bold">15. REVIEW/ULASAN � KORESPONDENSI � HAK KONTEN PENGGUNA</p>
<p>Dengan melengkapi pemesanan, Anda dengan ini menyatakan sepakat untuk menerima surat elektronik berisi ajakan untuk mengisi ulasan/konten review sehubungan dengan pemilihan Agen Travel, Maskapai, dan Hotel. Penampilan korespondensi atas review adalah diskresi Ruangguru semata-mata. Ruangguru dapat menampilkan korespondensi berisi tentang komentar, tingkat pelayanan dan nama pelanggan terkait. Anda dengan ini menyatakan menerima dan menyetujui untuk tunduk dalam Syarat dan Ketentuan review yang ada. Anda dengan ini menyatakan sepakat untuk menjamin bahwa </p>
<p>(i)	Anda memiliki dan menguasai semua hak atas review yang Anda berikan kepada Situs; </p>
<p>(ii)	konten review tersebut adalah akurat dan tidak mengandung penyesatan; dan</p>
<p>(iii)	penggunaan atau penampilan atau transmisi dari konten review tersebut tidak melanggar Syarat atau hukum peraturan yang berlaku dan Anda tidak mengakibatkan pelanggaran hak apapun atau menyebabkan cidera pihak manapun. Anda dengan ini memberikan hak kepada Ruangguru untuk bertindak apabila terdapat pihak yang melanggar hak Anda atau hak Ruangguru sehubungan dengan pelanggaran konten review dan Syarat yang ada. Anda dengan ini menyatakan bertanggung jawab secara pribadi atas konten review yang Anda berikan atau sampaikan.</p>
<p>Konten review yang diberikan akan dianggap bukan merupakan informasi rahasia dan Ruangguru tidak memiliki kewajiban untuk memperlakukan konten review sebagai suatu informasi rahasia atau suatu kepemilikan. Tanpa membatasi Ketentuan yang ada dalam Syarat, Ruangguru memiliki hak untuk menggunakan konten review sebagaimana dinilai patut termasuk namun tidak terbatas pada penghapusan, pemotongan, pengubahan, penolakan untuk menampilkan. Ruangguru tidak memiliki kewajiban untuk membayar konten review yang Anda sampaikan, termasuk namun tidak terbatas pada konten review yang diubah, dihapuskan, dipotong dan diubah. Ruangguru tidak memiliki kewajiban untuk memberikan atau mencantumkan atau mengumumkan penulis atau pihak ketiga lainnya.</p>
<p>Dalam kondisi apapun, Pengguna dengan ini menyatakan bahwa sehubungan dengan konten review </p>
<p>(a) Anda tidak membutuhkan atribusi atau pengenalan dalamnya ataupun dalam pekerjaan derivatifnya termasuk dalam perbaikan atau perbaharuan yang ada didalamnya </p>
<p>(b) Anda tidak keberatan dalam pemublikasian, penggunaan, penghapusan, pengubahan, pengeksploitasian konten review yang dilakukan Ruangguru, karyawan, pengganti dan penerima pengalihannya; </p>
<p>(c) Anda dengan ini melepaskan hak tuntut dan sepakat untuk tidak menuntut hak apapun dalam konten review; dan </p>
<p>(d) Anda dengan ini menyatakan melepaskan dan membebaskan Ruangguru, karyawan, afiliasi, pemegang hak, pengganti, dan penerima pengalihan dari tuntutan apapun sehubungan dengan konten review.</p>
<p class="bold">16. KETENTUAN LAINNYA</p>
<p>Anda dengan ini menyatakan sepakat untuk membebaskan dan melepaskan Ruangguru dari dan terhadap segala jenis tanggungan, kerusakan, atau kerugian termasuk biaya hukum yang diperlukan oleh Ruangguru sehubungan dengan tindakan, tidak dilaksanakannya suatu kewajiban atau pelanggaran yang Anda lakukan. Apabila penggunaan Situs ini adalah untuk kepentingan pihak ketiga ("Pihak Lain"), berupa anggota keluarga atau teman seperjalanan, maka Anda bertanggung jawab atas ketepatan informasi yang disediakan untuk digunakan. Anda memiliki kewajiban untuk memberitahukan mengenai Syarat yang berlaku kepada Pihak Lain tersebut. Tiap Pengguna yang menggunakan Situs ini untuk dan atas nama Pihak Lain dengan ini menyatakan sepakat untuk melepaskan dan membebaskan Ruangguru dari dan terhadap semua bentuk dan jenis pertanggungjawaban kerugian, tuntutan dan biaya (termasuk namun tidak terbatas pada biaya pembelaan), sehubungan dengan Pihak Lain atau kegagalan Pengguna untuk memenuhi semua kewajiban yang telah dinyatakan dalam Situs dan Syarat.</p>
<p>Anda wajib mematuhi semua peraturan perundangan yang berlaku dan Ruangguru tidak dapat dimintai pertanggungjawaban atas ketidaktahuan, kelalaian atau pelanggaran Pengguna maupun Pihak Lain.</p>
<p>Bahasa yang berlaku bagi penerapan Situs dan Syarat ini adalah bahasa Indonesia.</p>
<p>Dalam hal terdapat satu atau bagian dari Syarat ini yang tidak dapat dilaksanakan atau menjadi batal maka ketentuan tersebut tidak akan mempengaruhi berlakunya ketentuan lain dalam Syarat ini dan ketentuan lainnya tersebut akan tetap berlaku sejauh mana diperbolehkan oleh Peraturan Perundangan. Ketentuan yang tidak dapat berlaku atau batal akan digantikan dengan ketentuan yang baru dengan mempertimbangkan tujuan utama dari diberikannya ketentuan awal.</p>
<p>Ruangguru memiliki hak diskresi untuk mengubah, menangguhkan, memberhentikan Situs dan/atau bagian dari Situs, termasuk jasa atau produk yang tersedia dalam Situs, dan/atau penggunaan Situs, atau bagian darinya, tiap saat untuk alasan apapun tanpa melakukan pemberitahuan kepada Anda.</p>
<p>Dalam hal terdapat pemutusan, maka Anda akan tetap terikat pada kewajiban yang tertera dalam Syarat termasuk tiap penjaminan dan pelepasan berikut juga tiap penyampingan dan pembatasan tanggung jawab yang telah diterima oleh Anda.</p>
<p>Ruangguru juga tidak bertanggung jawab atas Anda atau pihak ketiga lainnya sehubungan dengan pemutusan akses Anda kepada Situs. Ruangguru memilik hak untuk mengubah dan mencabut ketentuan Syarat (atau bagian darinya) yang dianggap patut.</p>
<p>Kegagalan dalam melaksanakan hak Ruangguru bukan merupakan pengesampingan atau pelepasan dari hak terkait atau hak berikutnya. Anda tidak diperbolehkan untuk mengalihkan atau memberikan hak Anda kepada pihak lain. Kami dapat mengubah Syarat sewaktu-waktu dengan menampilkan perubahan pada Situs. Versi terbaru dari Syarat akan berlaku melampau versi yang telah lampau atau yang pernah ditampilkan sebelumnya.</p>
<p class="bold">17. FORCE MAJEURE</p>
<p>Ruangguru tidak bertanggung jawab atas segala kegagalan transaksi yang mengakibatkan kerugian di pihak Pengguna yang diakibatkan karena Force Majeure. Kondisi yang dikategorikan sebagai Force Majeure adalah bencana alam (banjir, gempa bumi), epidemik, kerusuhan, pernyataan perang, perang, perubahan peraturan yang berlaku, petir, angin topan, mogok buruh, demonstrasi dan sebagainya.</p>
<p>Jika dalam kasus Force Majeure Ruangguru tidak dapat memproses pesanan Anda, Ruangguru tidak akan bertanggung jawab atas kerugian yang disebabkan dengan cara apapun.</p>
<p class="bold">18. TENTANG RUANGGURU - FAQs</p>
<p>Setiap jasa disediakan oleh PT. Ruang Raya Indonesia, yaitu suatu perseroan terbatas yang didirikan berdasarkan hukum Republik Indonesia, memiliki domisili di Jakarta Pusat.</p>
<p>Apabila Anda memiliki pertanyaan lebih lanjut silakan merujuk pada FAQs.</p>
						  </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <?php $this->load->view('front/layout/contact');?>
                    <div class="blank clear" style="height: 20px;"></div>
                    <div class="social-side-box">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fruanggurucom&amp;width=300&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false&amp;appId=151390271591966" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:290px;" allowTransparency="true"></iframe>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="blank" style="height:30px;"></div>
</div>